#!/bin/bash

CLANG_FLAGS=" \
	`sdl2-config --cflags` \
	-fcolor-diagnostics -g3 \
	-Wno-c++11-narrowing -Wno-write-strings -Wno-reserved-user-defined-literal \
	-I$(realpath include) \
"

echo "____ Build ____"

mkdir -p out

cd src
clang++ -static -c *.cc $CLANG_FLAGS
clang *.o -o lagoon -lm -lmpack -Llib -L/usr/lib/x86_64-linux-gnu -lGL -lglfw `sdl2-config --libs`
rm *.o
cd ..

echo "____ End build ____"
