#!/bin/bash

cd src

VERSION=$(date +%-y.%-V.%-u)
PLATFORM=$(uname -m)

clang++ main.cc -o ../lagoon \
\
	-g3 \
	-Wno-c++11-narrowing -Wno-write-strings -Wno-reserved-user-defined-literal \
	-fno-caret-diagnostics -ferror-limit=3 \
\
	-isystem /home/$(whoami)/include/ \
	-I/home/$(whoami)/build/glad/include/ \
\
	-L/usr/local/lib/ \
	-L/home/$(whoami)/lib/ \
	-lHorde3D -lHorde3DUtils \
	-lGL -lglfw -lglad \
	-ldl \
\
	-DVERSION=\"$VERSION\" \
	-DPLATFORM=\"$PLATFORM\" \
$@
# capture clang error code
SUCCESS=$?

cd ..

# it always comes back
rm -rf .vscode

exit $SUCCESS