#!/bin/bash

# get access to some helper functions
# and shortcuts
source ~/.bashalias

TIMEFORMAT=%R

say()
{
	echo -e "$@"
}

say ""

say "Updating shaders..."
SHADERS=""
for i in src/shader/*.fs
do
	SHADERS="$SHADERS $i"
done
for i in src/shader/*.vs
do
	SHADERS="$SHADERS $i"
done
scomp compile/SHADER.c $SHADERS
say "Done updating shaders.\n"

say "Updating textures..."
TEXTURES=""
for i in src/texture/*.png
do
	TEXTURES="$TEXTURES $i"
done
for i in src/texture/*.jpeg
do
	TEXTURES="$TEXTURES $i"
done
tcomp compile/TEXTURE.c $TEXTURES
say "Done updating textures.\n"

contains s $@; if [[ $? -ne 0 ]]
then
	say "Compiling shaders..."
	TIMEA=$(date +%s%N)
	clang++ -Wno-everything -c compile/SHADER.c -DHL_COMPILE_RES -o compile/SHADER.o
	TIMEB=$(($(date +%s%N)-$TIMEA))
	TIME=$((TIMEB/1000000))
	say "Done compiling shaders in ${TIME} ms.\n"
fi

contains t $@; if [[ $? -ne 0 ]]
then
	say "Compiling textures..."
	TIMEA=$(date +%s%N)
	clang++ -Wno-everything -c compile/TEXTURE.c -DHL_COMPILE_RES -o compile/TEXTURE.o
	TIMEB=$(($(date +%s%N)-$TIMEA))
	TIME=$((TIMEB/1000000))
	say "Done compiling textures in ${TIME} ms.\n"
fi

say "Done."