#!/bin/bash

cd src

VERSION=$(date +%-y.%-V.%-u)
PLATFORM=$(uname -m)

clang++ main.cc -o ../lagoon \
\
	-DVERSION=\"$VERSION\" \
	-DPLATFORM=\"$PLATFORM\" \
\
	-g3 \
	-Wno-c++11-narrowing -Wno-write-strings -Wno-reserved-user-defined-literal \
\
	-Iinclude \
	-L/usr/lib/x86_64-linux-gnu/cmake/ \
	-lglfw -ldl \
	-lHorde3D -lHorde3DUtils \
$@

# capture clang error code
SUCCESS=$?

cd ..

# it always comes back
rm -rf .vscode

exit $SUCCESS